### ISSUE TITLE
Plugin calls `flush` more than necessary

### ISSUE THREAD

**Issue by alexbestul** [dimaros-bv/vue3-application-insights#10]
Currently, the plugin flushes the App Insights telemetry buffer after every navigation event. Documented best practice is to let the App Insights client auto-flush as needed, and only to explicitly flush in special circumstances, such as when the app is shutting down.

> Normally, the SDK sends data at fixed intervals, typically 30 seconds, or whenever the buffer is full, which is typically 500 items. In some cases, you might want to flush the buffer. An example is if you're using the SDK in an application that shuts down.

See: https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#flushing-data

I'm working on a change for this and should have a PR ready soon.

**Comment by alexbestul** [comment]
Opened #11

**Comment by alexbestul** [comment]
Closed #11 and opened #12.

**Comment by ebuzyuma** [comment]
#12 is merged and deployed.
Version [1.0.4](https://www.npmjs.com/package/vue3-application-insights/v/1.0.4) is available with the fix.
