### ISSUE TITLE
appName is not seted

### ISSUE THREAD

**Issue by FisherMS** [dimaros-bv/vue3-application-insights#6]
I found the default appName is random?

![image](https://github.com/dimaros-bv/vue3-application-insights/assets/12068896/db2793a5-caf9-4625-81e3-ad1907aea7dc)

```js
const aiOptions: AppInsightsPluginOptions = {
  appName: "BIReportApp", // Prefix for route events
  connectionString: "InstrumentationKey=24.....",
  //router: router,
  trackAppErrors: true,
};

app.use(AppInsightsPlugin, aiOptions)
```

**Comment by ebuzyuma** [comment]
@FisherMS, this is not related to the `appName` in settings.
The name of the component you see on the application map is a cloud role. And in your case, it's the name of the hosting plan (as far as I can infer).
Follow this [MS guide to change cloud role name](https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net#set-or-override-cloud-role-name).

AppName you can see if you dig into the user timeline: Users -> View more Insights -> View User timeline.
Or in the logs in the `name` column in `pageViews`.

**Comment by FisherMS** [comment]
Hi @ebuzyuma 

In my case the name is the ApplicationInsights Service Name.
Yes in C# code , I can modify the RoleName for the WebApp Service . It can display on Applicaation Map.

Is there a way to modify the RoleName in the SDK you provided?

Thank you very much.

**Comment by ebuzyuma** [comment]
Oh, I see it now. You can indeed do the same with javascript.

Because I see that `cloudRole` and `cloudRoleInstance` the options that someone also could utilize, I opened PR #7 to address that.

In the meantime, if you need that right away, you could use `onLoaded` option:
```js
const aiOptions: AppInsightsPluginOptions = {
  ...
  onLoaded: (appInsights) => {
    appInsights.addTelemetryInitializer((envelope) => {
      envelope.tags["ai.cloud.role"] = "your role name";
      envelope.tags["ai.cloud.roleInstance"] = "your role instance";
    });
  },
};
```

**Comment by FisherMS** [comment]
It's work well. Thank you very much.

```js
onLoaded: (appInsights) => {
    appInsights.addTelemetryInitializer((envelope) => {
      var tags = envelope.tags;
      if (tags) {
        tags["ai.cloud.role"] = "RoleAppName";
        tags["ai.cloud.roleInstance"] = "RoleInstance";
      }
    });
  },

```
