### ISSUE TITLE
Remove deprecated `next` parameter in `beforeEach` navigation guard

### ISSUE THREAD

**Issue by alexbestul** [dimaros-bv/vue3-application-insights#8]
The `next` parameter in vue router's `beforeEach` navigation guard is officially deprecated.

See: https://router.vuejs.org/guide/advanced/navigation-guards.html#Optional-third-argument-next

The parameter is still allowed by Vue's router implementation, but it appears to unsupported by NuxtJS's router implementation. In a NuxtJS app, `next` is always `undefined`. Attempting to invoke `next()` on line 95 causes an error and the navigation is cancelled.

https://github.com/dimaros-bv/vue3-application-insights/blob/f0497d36c03b885f9999662bcaf7f86a446b992f/src/index.ts#L90-L96

This plugin is currently unusable in a NuxtJS app. Removing the `next` parameter will allow use in a NuxtJS app with no negative consequence for Vue3 apps.

**Comment by alexbestul** [comment]
Opened #9 with proposed change.

**Comment by ebuzyuma** [comment]
Thanks a lot for the proposed changes!
They are merged and version [1.0.3](https://www.npmjs.com/package/vue3-application-insights) is now available.
